config/routes.rb
Rails.application.routes.draw do
  resources :statuses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/status.rb
class Status < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Treebook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-default navbar-main main-header">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navbar-main-content">


        <ul class="nav navbar-nav  navbar-left-dropdowns">
          <li>
            <%=	 link_to "Statuses", statuses_path %>
          </li>
        </ul>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
  </nav>

  <div class="container">

    <%= yield %>

  </div>
  </body>
</html>

app/views/statuses/_form.html.erb
<%= form_for(status) do |f| %>
  <% if status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name  %>
    <%= f.text_field :name  ,  class: 'form-control' %>

    <!--<%= text_field_tag :login_aei, "", class: 'form-control' %>-->

  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content ,  class: 'form-control'%>
  </div>

  <div class="actions">
    <%= f.submit 'Submit' , :class =>  'btn btn-primary' %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<p id="notice" class="">

<div class="alert alert-success">
  <strong>Messages : </strong> <%= notice %>
</div>


</p>


<div class="page-header">
<h1>Statuses</h1>
  <p><%= link_to 'New Status', new_status_path %>
</div>

<% @statuses.each do |status| %>
<div class="col-sm-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <strong><%= status.name %></strong>
    </div>
    <div class="panel-body status" >

      <%= status.content %>

      <ul class="list-inline list-unstyled">
        <li><span><i class="glyphicon glyphicon-calendar"></i> <span class="text-muted">posted <%= time_ago_in_words(status.created_at) %> ago</span> </span></li>
        <li>|</li>
        <span class="admin">
          <%= link_to 'Edit', edit_status_path(status) %>
          <%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %>
        </span>
      </ul>


    </div><!-- /panel-body -->

  </div><!-- /panel panel-default -->
</div>
<% end %>


<!--<table class="table table-striped">-->
  <!--<thead>-->
    <!--<tr>-->
      <!--<th>ID</th>-->
      <!--<th>Posted</th>-->
      <!--<th>Name</th>-->
      <!--<th>Content</th>-->
      <!--<th colspan="3"></th>-->
    <!--</tr>-->
  <!--</thead>-->

  <!--<tbody>-->
    <!--<% @statuses.each do |status| %>-->
      <!--<tr class="status">-->
        <!--<td><%= status.id %></td>-->
        <!--&lt;!&ndash;<td><%= status.created_at %></td>&ndash;&gt;-->
        <!--<td><%= time_ago_in_words(status.created_at) %></td>-->
        <!--<td><%= status.name %></td>-->
        <!--<td><%= status.content %></td>-->
        <!--<td><%= link_to 'Show', status %></td>-->

        <!--<td class="admin"><%= link_to 'Edit', edit_status_path(status) %></td>-->
        <!--<td class="admin"><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      <!--</tr>-->
    <!--<% end %>-->
  <!--</tbody>-->
<!--</table>-->

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<div class="alert alert-success">
  <strong>Messages : </strong> <%= notice %>
</div>


<p>
  <strong>Name:</strong>
  <%= @status.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>